[workers]
worker ansible_host=192.168.56.101 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/lab4_key

[db]
db ansible_host=192.168.56.102 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/lab4_key

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3