#cloud-config

hostname: ${hostname}
manage_etc_hosts: true

users:
  - name: ansible
    gecos: "Ansible Automation User"
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups:
      - sudo
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_public_key}

package_update: true
package_upgrade: false

packages:
  - python3
  - curl
  - git
  - ufw

runcmd:
  - ufw --force enable
  - ufw allow OpenSSH
